bookings/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'bookings'

urlpatterns = [
    path('table_bookings/', views.table_bookings, name='table_bookings'),
    path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
    path('register/', views.register, name='register'),
    path(
        'accounts/profile/',
        views.redirect_registered_user,
        name='redirect_registered_user'
    ),
    path(
        'booking_successful/',
        views.booking_successful,
        name='booking_successful'
    ),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),
    path(
        'logout.html',
        views.logout_page,
        name='logout_page'
    ),
    path('view_bookings/', views.view_bookings, name='view_bookings'),
    path(
        'booking/update/<int:booking_id>/',
        views.edit_booking,
        name='edit_booking'
    ),
    path(
        'booking_updated_successfully/',
        views.booking_updated_successfully,
        name='booking_updated_successfully'
    ),
    path(
        'confirm-delete/<int:booking_id>/',
        views.confirm_delete,
        name='confirm_delete'
    ),
    path(
        'booking-deleted/',
        views.booking_deleted_successfully,
        name='booking_deleted_successfully'
    ),
]

restoamore/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('restaurant.urls', namespace='restaurant')),
    path('', include('bookings.urls', namespace='bookings'))
]

bookings/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime


class Booking(models.Model):
    """
    Model for table bookings
    """
    TIMES = []
    for hrs in range(17, 22):
        for min in range(0, 60, 30):
            if hrs < 21 or (hrs == 21 and min == 0):
                time_value = datetime.time(hrs, min)
                time_text = (
                    f"{hrs % 12 or 12}:{min:02d}"
                    f"{'AM' if hrs < 12 else 'PM'}"
                )
                TIMES.append((time_value, time_text))

    PAX_CHOICES = [(i, str(i)) for i in range(1, 11)]

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    guest_last_name = models.CharField(max_length=400, default="", null=False)
    phone_number = models.CharField(max_length=20, null=False)
    date = models.DateField(default=datetime.date.today)
    time = models.TimeField(choices=TIMES, default=datetime.time(17, 30))
    num_people = models.IntegerField(
        choices=PAX_CHOICES,
        null=False,
        default=2,
        help_text="For reservations of bigger parties please call us directly."
    )

    class Meta:
        ordering = ['date', 'time']

    def __str__(self):
        return f'{self.user.username} - {self.date} {self.time}'

bookings/forms.py
from django import forms
from .models import Booking
import datetime


class BookingForm(forms.ModelForm):
    class Meta:
        model = Booking
        fields = [
            'guest_last_name',
            'phone_number',
            'date',
            'time',
            'num_people'
        ]
        widgets = {
            'date': forms.DateInput(attrs={'type': 'date'})
        }

bookings/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Booking
from .forms import BookingForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login
from django.core.exceptions import PermissionDenied


# Create your views here
@login_required
def table_bookings(request):
    """
    View for displaying booking form
    """
    if request.method == 'POST':
        form = BookingForm(request.POST)
        if form.is_valid():
            booking = form.save(commit=False)
            booking.user = request.user
            booking.save()
            return redirect('bookings:booking_successful')
    else:
        form = BookingForm()

    context = {'form': form}

    return render(request, 'bookings/table_booking.html', context)


def register(request):
    """
    View for displaying the register form for users to create an account
    """
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('bookings:table_bookings')
    else:
        form = UserCreationForm()

    context = {'form': form}

    return render(request, 'registration/register.html', context)


def redirect_registered_user(request):
    """
    View for displaying table booking form after user registered
    """
    return render(request, 'bookings/table_booking.html')


def booking_successful(request):
    """
    View for displaying the successful booking page
    """
    latest_booking = Booking.objects.latest('id')

    context = {'latest_booking': latest_booking}

    return render(request, 'bookings/booking_successful.html', context)


def logout_page(request):
    return render(request, 'registration/logout.html')


def view_bookings(request):
    """
    View for displaying the list of bookings
    """
    user_bookings = Booking.objects.filter(user=request.user)

    context = {'user_bookings': user_bookings}

    return render(request, 'bookings/view_bookings.html', context)


@login_required
def edit_booking(request, booking_id):
    """
    View for displaying booking form to be able to edit exsisting booking
    """
    booking = get_object_or_404(Booking, id=booking_id)

    if request.user != booking.user:
        raise PermissionDenied

    if request.method == 'POST':
        form = BookingForm(request.POST, instance=booking)
        if form.is_valid():
            form.instance.status = 0
            form.save()
            return redirect('bookings:booking_updated_successfully')
    else:
        form = BookingForm(instance=booking)

    context = {'form': form}

    return render(request, 'bookings/table_booking.html', context)


def booking_updated_successfully(request):
    """
    View for displaying success message after booking was successfully updated
    """
    return render(request, 'bookings/booking_updated_successfully.html')


def confirm_delete(request, booking_id):
    """
    View for confirming that the booking should be deleted
    """
    booking = get_object_or_404(Booking, id=booking_id)

    if request.user != booking.user:
        raise PermissionDenied

    if request.method == 'POST':
        if 'confirm_delete' in request.POST:
            booking.delete()
            return redirect('bookings:booking_deleted_successfully')

    context = {'booking': booking}

    return render(request, 'bookings/confirm_delete.html', context)


def booking_deleted_successfully(request):
    """
    View for displaying a success message after booking deletion
    """
    return render(request, 'bookings/booking_deleted_successfully.html')

bookings/templates/bookings/booking_deleted_successfully.html
{% extends "base.html" %}
{% block title %}Booking Deleted Successfully{% endblock %}

{% block content %}
<div class="container booking-deleted-container mt-5">
    <p class="success-message">Your booking has been successfully deleted!</p>
    <p><a href="{% url 'bookings:view_bookings' %}" class="view-booking-link">View Current Bookings</a></p>
</div>
{% endblock %}

bookings/templates/bookings/booking_successful.html
{% extends "base.html" %}
{% block title %}Booking Successful{% endblock %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <h2 class="card-title text-center">Booking Successful</h2>
                    <p class="text-center">Your table has been booked successfully!</p>
                    {% if latest_booking %}
                        <p class="text-center">Date: {{ latest_booking.date }}</p>
                        <p class="text-center">Time: {{ latest_booking.time }}</p>
                        <p class="text-center">Number of People: {{ latest_booking.num_people }}</p>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

bookings/templates/bookings/booking_updated_successfully.html
{% extends "base.html" %}
{% block title %}Booking Updated{% endblock %}

{% block content %}
<div class="container booking-updated">
    <div class="alert alert-success" role="alert">
        Booking updated successfully!
    </div>
    <p><a class="btn btn-primary" href="{% url 'bookings:view_bookings' %}">View Bookings</a></p>
</div>
{% endblock %}

bookings/templates/bookings/confirm_delete.html
{% extends "base.html" %}
{% block title %}Confirm Delete Booking{% endblock %}

{% block content %}
<div class="confirm-delete-container">
    <p>Are you sure you want to delete the booking for {{ booking.date }}?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit" name="confirm_delete" value="yes">Yes, Delete Booking</button>
        <a href="{% url 'bookings:view_bookings' %}">Cancel</a>
    </form>
</div>
{% endblock %}

bookings/templates/bookings/table_booking.html
{% extends "base.html" %}
{% block title %}Book a Table{% endblock %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <h2 class="card-title text-center">Book Table</h2>
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary">Book</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

bookings/templates/bookings/view_bookings.html
{% extends "base.html" %}
{% block title %}Your Bookings AMORE{% endblock %}

{% block content %}
<div class="booking-container">
    <ul class="booking-list">
        {% for booking in user_bookings %}
            <li class="booking-item">
                <div class="booking-details">
                    <strong>Date:</strong> {{ booking.date }}<br>
                    <strong>Time:</strong> {{ booking.time }}<br>
                    <strong>Number of People:</strong> {{ booking.num_people }}<br>
                </div>
                <form method="post" action="{% url 'bookings:edit_booking' booking.id %}" class="edit-form">
                    {% csrf_token %}
                    <button type="submit">Edit Booking</button>
                </form>
                <form method="post" action="{% url 'bookings:confirm_delete' booking.id %}" class="delete-form">
                    {% csrf_token %}
                    <button type="submit">Delete Booking</button>
                </form>
            </li>
        {% empty %}
            <li class="no-booking">No bookings found.</li>
        {% endfor %}
    </ul>
    <div class="add-booking-link">
        <a href="{% url 'bookings:table_bookings' %}">Add new Table Booking</a>
    </div>
</div>
{% endblock %}