bookings/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'bookings'

urlpatterns = [
    path('table_bookings/', views.table_bookings, name='table_bookings'),
    path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
    path('register/', views.register, name='register'),
    path(
        'accounts/profile/',
        views.redirect_registered_user,
        name='redirect_registered_user'
    ),
    path(
        'booking_successful/',
        views.booking_successful,
        name='booking_successful'
    ),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),
    path(
        'logout.html',
        views.logout_page,
        name='logout_page'
    ),
    path('view_bookings/', views.view_bookings, name='view_bookings'),
    path(
        'booking/update/<int:booking_id>/',
        views.edit_booking,
        name='edit_booking'
    ),
    path(
        'booking_updated_successfully/',
        views.booking_updated_successfully,
        name='booking_updated_successfully'
    ),
    path(
        'confirm-delete/<int:booking_id>/',
        views.confirm_delete,
        name='confirm_delete'
    ),
    path(
        'booking-deleted/',
        views.booking_deleted_successfully,
        name='booking_deleted_successfully'
    ),
]

restaurant/urls.py
from django.urls import path
from . import views

app_name = 'restaurant'

urlpatterns = [
    path('', views.about_view, name='home'),
    path('food/', views.foodmenu, name='food'),
    path('drinks/', views.beveragemenu, name='drinks'),
    path('contact/', views.contact, name='contact'),
]

restoamore/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('restaurant.urls', namespace='restaurant')),
    path('', include('bookings.urls', namespace='bookings'))
]

templates/base.html
{% load static %}

<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Amore Italian Restaurant Site">
    <meta name="keywords" content="restaurant, italian, pasta, drinks, pizza">

    <title>{% block title %}{% endblock %}</title>
    
    <!-- Google Fonts-->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=DM+Serif+Display:ital@0;1&family=Red+Hat+Display&display=swap" rel="stylesheet">

    <!-- Font Awesome -->
    <script src="https://kit.fontawesome.com/a1bd9d75a9.js" crossorigin="anonymous"></script>
 
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" 
    integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    <!-- Global CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

    <!-- Bootstrap JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" 
    integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

</head>

<body>
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg sticky-top">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'restaurant:home' %}">
          <div class="logo-container">
            <img src="{% static 'images/resto-amore-logo.png' %}" alt="Logo" class="logo-image">
          </div>
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
          <ul class="navbar-nav">
            {% if user.is_authenticated %}
              <li class="nav-item"><a class="nav-link" aria-current="page" href="{% url 'restaurant:food' %}">EAT</a></li>
              <li class="nav-item"><a class="nav-link" aria-current="page" href="{% url 'restaurant:drinks' %}">DRINK</a></li>
              <li class="nav-item"><a class="nav-link" aria-current="page" href="{% url 'restaurant:contact' %}">CONTACT</a></li>
              <li class="nav-item"><a class="nav-link" aria-current="page" href="{% url 'bookings:view_bookings' %}">BOOKINGS</a></li>
              <li class="nav-item"><a class="nav-link" aria-current="page" href="{% url 'bookings:logout' %}">LOGOUT</a></li>
            {% else %}
              <li class="nav-item"><a class="nav-link" aria-current="page" href="{% url 'restaurant:food' %}">EAT</a></li>
              <li class="nav-item"><a class="nav-link" aria-current="page" href="{% url 'restaurant:drinks' %}">DRINK</a></li>
              <li class="nav-item"><a class="nav-link" aria-current="page" href="{% url 'restaurant:contact' %}">CONTACT</a></li>
              <li class="nav-item bg-light-subtle rounded"><a class="nav-link active btn" aria-current="page" href="{% url 'bookings:table_bookings' %}">BOOK A TABLE</a></li>
            {% endif %}
          </ul>
        </div>
      </div>
  </nav>

  <!-- About section on landig page-->
  {% block content %} 
  {% endblock %}

  <!-- Footer -->
  <footer>
      <div class=".container text-center">
        <div class="footer fixed-bottom">
          <!-- Social Media Icons-->
          <div class="footer-icon d-flex justify-content-center">
            <a href="https://facebook.com" target="_blank" rel="noopener" aria-label="Visit our Facebook page (opens in a new tab)"><i class="fa-brands fa-facebook" style="color: #050505;"></i></a>
            <a href="https://instagram.com" target="_blank" rel="noopener" aria-label="Visit our Instagram page (opens in a new tab)"><i class="fa-brands fa-instagram" style="color: #050505;"></i></a>
          </div>
          <!-- Copyright -->
          <div id="copyright">
            <p>&copy; 2024 M.K with amore</p>
          </div>
        </div>
      </div>
  </footer>
      
</body>

</html>